sankey/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import us_energy_viz

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('us_energy_viz.urls')),
                  # path('', us_energy_viz.urls),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

us_energy_viz/urls.py
from django.urls import path

from . import views

app_name = 'us_energy_viz'

urlpatterns = [
    path('', views.index, name='index'),
    path('about_us/', views.about, name='about_us'),
    path('charts/', views.charts, name='charts'),
    path('license/', views.license, name='license'),
    path('contact/', views.contact, name='contact'),
]

us_energy_viz/models.py
from django.db import models

# Create your models here.

us_energy_viz/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'us_energy_viz/index.html')
		
	
def about(request):
    return render(request, 'us_energy_viz/about.html')
	
	
def license(request):
    return render(request, 'us_energy_viz/license.html')
	

def charts(request):
    return render(request, 'us_energy_viz/stackedcharts.html')


def contact(request):
    return render(request, 'us_energy_viz/contact.html')

us_energy_viz/templates/us_energy_viz/about.html
{% extends 'us_energy_viz/base.html' %}

{% load static %}

{% block title %}
About
{% endblock %}

{% block home_content %}
<div class="body_wrapper">
    <div class="site_wrapper fadeOnLoad">
        <!-- <div id="particles-js"></div> -->
        <div class="main_wrapper">
            <div class="content_wrapper">
                <div class="container">
                    <div class="content_block row no-sidebar">
                        <div class="fl-container">
                            <div class="row">
                                <div class="posts-block">
                                    <div class="contentarea">
                                        <div class="page_title">
                                            <h1>About this project</h1>
                                        </div>
                                        <!-- .page_title -->

                                        <article class="contentarea">
                                            <p>At a time when many people propose transforming the world’s energy
                                                system, it is instructive to consider past energy transitions. The
                                                history of past U.S. energy transitions can help us understand our
                                                potential future pathways.</p>
                                            <p>The U.S. Energy History Visualization project is conducted by members of
                                                the University of Chicago’s Center for Robust Decision-making on Climate
                                                and Energy Policy (RDCEP), under the direction of Assoc. Professor Liz
                                                Moyer, Dept. of the Geophysical Sciences. The research lead on the
                                                project is Robert Suits, U. Chicago Dept. of History. Graphics were
                                                built by Nathan Matteson, DePaul University College of Computing and
                                                Digital Media, and members of U. Chicago’s Research Computation Center,
                                                including Milson Munakami, Sergio Elahi and Ramesh Nair.
                                                See <a href="http://www.rdcep.org/" target="_blank">www.rdcep.org</a>
                                                for further information.</p>
                                            <p>The energy history tool consists of an interactive Sankey diagram of U.S.
                                                per capita primary energy use from 1800&ndash;2017: a mapping of primary
                                                energy sources to sectoral uses. Data on sectoral energy use before 1990
                                                was compiled from historical sources including the U.S. Census and the
                                                Census Bureau’s Historical Statistics of the United States. Data for
                                                individual years after 1990 is provided by the <a
                                                    href="https://flowcharts.llnl.gov/commodities/energy"
                                                    target="_balnk">Lawrence Livermore
                                                    National Laboratory (LLNL)</a>. The manuscript describing the
                                                research is
                                                currently in preparation (<span style="font-family:sans-serif;font-weight: bold;">&#8220;</span>Energy Transitions in U.S. History<span style="font-family:sans-serif;font-weight: bold;">&#8221;</span>, Suits,
                                                Matteson, and Moyer, 2020).</p>
                                            <p>To use the graph, play an animation with the <span style="font-family:sans-serif;font-weight: bold;">&#8220;</span>play<span style="font-family:sans-serif;font-weight: bold;">&#8221;</span> button at bottom
                                                left, or drag the timeline slider to control the animation by hand.
                                                Black circles along the timeline mark years of especial interest; click
                                                these to open up additional information. To more fairly show the energy
                                                requirements of the different sectors, the default setting for the
                                                animation is to allocate the waste heat from energy generation to those
                                                sectors that use electricity. Click the switch at bottom left to turn
                                                off this feature. The agricultural sector here represents on-field
                                                energy use and does not include embodied energy in fertilizer.</p>
                                            <p>The Sankey uses units of per capita energy use to best show the structure
                                                of the energy sector. Per capita energy use rose by ×3 from 1800-2017,
                                                but note that the U.S. population also grew by ×60 over this time
                                                period. The stacked bar chart at bottom shows the evolution of fuel
                                                usage, i.e. the fractional contribution of each fuel to the U.S. energy
                                                mix. The U.S. was primarily wood-powered through the late 1890s,
                                                primarily coal-powered through the 1930s, and now is powered largely by
                                                petroleum (oil) and natural gas.</p>
                                            <p>The visualization tool is in beta; we welcome comments and suggestions
                                                sent to <a
                                                    href="mailto:rdcep-info@uchicago.edu?Subject=Question%20regarding%20US%20Sankey"
                                                    target="_top">rdcep-info@uchicago.edu</a>.</p>
                                        </article>                                       

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clear">&nbsp;</div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block customscript %}
<!-- <script type="text/javascript" src="{% static 'us_energy_viz/js/particles.js' %}"></script>

<link rel="stylesheet" href="{% static 'us_energy_viz/css/themes/default/default.css' %}" type="text/css"
    media="screen" />
<script>
    jQuery(document).ready(function ($) {
        particleBody_init();
        
    });
</script> -->
{% endblock %}

us_energy_viz/templates/us_energy_viz/base.html
{% load static %}

<!DOCTYPE html>
<html dir="ltr" lang="en-US">

<head>
    <!-- Meta Tags -->
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Support for mobile touch devices -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="viewport" content="user-scalable=no, width=device-width, initial-scale=1, maximum-scale=1, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="description" content="Visualization of US Energy Consumption" />
    <meta name="keywords"
        content="US Energy Evolution Visualization, US Energy Evolution Viz, US Energy Viz, US Energy Visualization,Visualization of US Energy Consumption, US Energy Consumption app, US Energy Usage app, US Energy Consumption web app, US Energy web app, US Energy web, uchi, uchicago, computation center, computation, hpc, hpcmatters, research, research computation center, research center, uchicago research, research uchicago" />
    <meta name="author" content="RCC" />
    <meta name="robots" content="noindex,follow" />

    <!-- Page Title -->
    <title>
        {% block title %}{% endblock %} | Visualization of US Energy Consumption
    </title>

    <!--
      .+((<<+==sszzhhhDDhhDDDhhhDDDDDDhhDDDDhhDDDhhhzzss==++<<(++.
      Nh=++>(++++''..                              ..''++++)<++=hN
      N           +''..'+<=zhDDhz=(..++szhDhz=(+'.. ...          N
      N           BNNNNNBBNDzNNhBNN==NBs=B=BsNBDNNNNNNh          N
      N    +('    BD+h+N+sz+hN(((BN==NNB+sBs(N+=DD=hNNh          N
      N   =NNN'hh+Bh<D=N+NNs=h+hzBN==NNNhzNN(D==N(s<NNh+DhDBh'   N
      N   +sz+ <<.BBzzDsB+hs++NzB=N==Nhzz=D=s=NBDhDhNNh+Ds<'     N
      N           B<DN=<h(Bzh(+zD+N==N.Dz=Ns+zszzhs(hBh          N
      N     .     BBsDssDDBDBsNzNsB==N=shzNDDBD<zz(=BBh          N
      N   <NNh.++'BNh<D(=zz<B<Dh<sN==N+ND=sD+B=B=NhBBNh=DDDBh'   N
      N   <BNh.zz'BN(=N(h<D<B=z(+(N==N+D<=+D+B(z+B<=sNh+hs(' .   N
      N           BNNDNBNNNNNNNNNNN==NDNBNNNNNBBDBhDNNh          N
      N           DBDDhs+<++'. .+(=<<+('. .'++<+szhDBNh          N
      N                                                          N
      N               .++.      +(+zss+<''       ++'             N
      N           +szDNNNB'    zhhNz+sBN+.   'zBBNNNBh<.         N
      N         '+DNNNNNNN+  +=<(+=zNNNNs'   =NNNNNNNNNBs+       N
      N      '+hNNNNNNNNNDz+  ++''<==zNNz  ++h=sNNNNNNNNNB<      N
      N   '<hNDhNNNNNNNN+   h+    '+zBNNz' +'  =NNNNNNNNNBzs+    N
      N  .((+'+BNNNNNNNN(  .sND(  +=hNNz( +D( <NNNNNNNNNN=Dh<(.  N
      N    (sNNNNNNNNNNNhshDsBNN+zNNNNNs+=BNBNNNNNNNNNNNBN=zN=   N
      N  (s=<=BNNNNNNNNNNNNNNNNB(hNNNNNz<BNNNNNNNNNNNNNNB=N=<hh' N
      N    (DsDNNNNNNNNNNNNNNNND(NNNNNNND<NNNNNNNNNNNNBBNzzN= .' N
      N  +hs+hzDNBNNzNNNNNNNNNN<DNNNNNNBB<NNNNNNNNNNzNB+NN<NN(   N
      Bs.+. zD'NBsD<BDzNzDNBNNNs+zNNNNNN<=NNNNNNNNsNh<B+NNzsND  =B
      zD   +N++N=s+Ns=NszN+DNNNN(BNs+NNNz+NNNNNNNND+DB+'hNN+NN  hz
      <N' 'N< +z(=++h=(zD(hz(s=B=+D=sDNB+zNNNDNNz=NB<+N<sz=.hN 'N<
      .B= +z  'N<N+D=+B+<=<zshB<=D<ND<+<+(NN+<NhNh+(ND+'+D+ +D +B.
      =B.+.   B(B=(<=sz(+Nh+hNN+z(Nz=N<<h=zh=sz+(D+zs<zNz   +.B=
      .Bs     ++=BBNzsNz(NN'=NNh+(NDNN+Ds+sNz(<==D+<+DNN+'   =B.
      +N(    .s<(+=zhBNNNNh+<BNz+NNNz=D+<NN(+=zD+sBNDzz+   +N(
      +N+    =s    .(=sDNNNBsszBDND=NB+DB<+DBs<++'  hz   +B=
          =B+    '   '++=z=<<<++sDsDNBNNNNB=hs+        <.  +Bs
          +N<        (hzssDNNNBhzBNNNNNNN=+. .(<.        +B=
          +Bs.        +=hz++.(++=BNNNNNNNDhhz+        .=B(
          .sB<        '+'..(<<+zDNNz<+++++'         +Dz'
              +hD(       +zND(  'zDBhsBDssNNz'      +hD+
              +zD<.      +hNDhh( <z. +=ss+     .<Dh(
                  '=Bz(.     '+'  +(DD        .(sBs+
                      +=Dz++        (++    .++zDs+
                      .<sDhs=>+'    '+<shDs<.
                          .+<=zDDDDz=<+.
      -->

    <!-- Favicon and Touch Icons -->
    <link rel="shortcut icon" href="{% static 'us_energy_viz/img/favicon.ico' %}" type="image/vnd.microsoft.icon" />

    <!-- Stylesheet -->

    <link rel="stylesheet" href="{% static 'us_energy_viz/css/font-awesome.min.css' %}" type="text/css" media="all" />

    <link rel="stylesheet" href="{% static 'us_energy_viz/css/theme.css' %}" type="text/css" media="all" />
    <!--<link rel="stylesheet" href="{% static 'us_energy_viz/css/responsive.css' %}" type="text/css" media="all" />-->

    <link rel="stylesheet" href="{% static 'us_energy_viz/css/jquery-ui.min.css' %}" type="text/css" media="all" />

    <!-- CSS | Style css. This is the file where you can place your own custom css code. Just uncomment it and use it. -->
    <link rel="stylesheet" href="{% static 'us_energy_viz/css/style.css' %}" type="text/css" media="all" />

    <!-- CSS for Sankey -->
    <link rel="stylesheet" href="{% static 'us_energy_viz/sass/main.css' %}" type="text/css" media="all" />

    <link rel="stylesheet" href="{% static 'us_energy_viz/css/playbutton.css' %}" type="text/css" media="screen" charset="utf-8">
    <!-- CSS for Slider -->
    <!-- <link rel="stylesheet" href="{% static 'us_energy_viz/css/d3.slider.css' %}" type="text/css" media="all" /> -->
    <!-- Dynamic checkbox starts-->
   <link rel="stylesheet" href="{% static 'us_energy_viz/css/simple-button-radios.css' %}" type="text/css" media="screen" charset="utf-8">
   <link rel="stylesheet" href="{% static 'us_energy_viz/css/radios.css' %}" type="text/css" media="screen" charset="utf-8">
   <!-- Dynamic checkbox ends-->
   <!-- <link rel="stylesheet" href="{% static 'us_energy_viz/css/d3.slider.css' %}" type="text/css" media="all" /> -->
  <link rel="stylesheet" href="{% static 'us_energy_viz/css/kendo.default-v2.min.css' %}" type="text/css" media="screen" charset="utf-8">

    <!-- external javascripts -->
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery/jquery-3.3.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery/jquery.form.js' %}"></script>

    <!-- jQuery Easing JS-->
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery.easing.1.3.min.js' %}"></script>

    <!-- jQueryUI -->
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery-ui.min.js' %}"></script>

    <!-- Cookies.js -->
    <script type="text/javascript" src="{% static 'us_energy_viz/js/cookies.min.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Custom Fonts -->
    <!-- <link href="https://cloud.typography.com/6526092/7025152/css/fonts.css" rel="stylesheet"> -->
    <script type="text/javascript" src="{% static 'us_energy_viz/fonts/Fieldwork.js' %}"></script>

      <!-- Dynamic Charts -->
    <script type="text/javascript" src="{% static 'us_energy_viz/js/core.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/charts.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/animated.js' %}"></script>

    <!-- D3.js -->

	<!-- bootstrap css and js -->
	<!--<link rel="stylesheet"  href="{% static 'us_energy_viz/css/bootstrap.min.css' %}" type="text/css">  -->
	<!-- Latest compiled and minified JavaScript -->
	<!-- <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>  -->
  <!-- Dynamic checkbox starts-->

   <script type="text/javascript" src="{% static 'us_energy_viz/js/simple-button-radios.js' %}"></script>
 <script type="text/javascript" src="{% static 'us_energy_viz/js/kendo.all.min.js' %}"></script>
   <!-- Dynamic checkbox ends-->
</head>

<body>

    {% include 'us_energy_viz/header.html' %}

    {% block home_content %}
    {% endblock %}

    {% include 'us_energy_viz/preloader.html' %}

    {% include 'us_energy_viz/footer.html' %}

    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery.mousewheel.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery.waypoints.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/theme.js' %}"></script>
    <script type="text/javascript" src="{% static 'us_energy_viz/js/jquery.ui.totop.js' %}"></script>

    <!-- Include JQuery Hammerjs adapter for mobile touch-->
    <script src="{% static 'us_energy_viz/js/hammer.min.js' %}"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-144831754-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-144831754-1');
    </script>


    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <!--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"-->
    <!--integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">-->
    <!--</script>-->

    <!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->
    <!--<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>-->

    <script>
        $(document).ready(function () {
            // $().UItoTop({
            //     easingType: "easeOutQuart"
            // });
            $("[data-toggle='tooltip']").tooltip();


	$(document).keydown(function(event) {

        if (event.ctrlKey==true && (event.which == '61' || event.which == '107' || event.which == '173' || event.which == '109'  || event.which == '187'  || event.which == '189' || event.which=='0' ) ) {

		  event.preventDefault();

	     }

	});

	$(window).bind('mousewheel DOMMouseScroll', function (event) {

	       if (event.ctrlKey == true || event.which=='0' ) {

		   event.preventDefault();
	       }
	});
 });
    </script>

    {% block customscript %}
    {% endblock %}
</body>

</html>

us_energy_viz/templates/us_energy_viz/contact.html
{% extends 'us_energy_viz/base.html' %}

{% load static %}

{% block title %}
Contact
{% endblock %}

{% block home_content %}
<div class="body_wrapper">
    <div class="site_wrapper fadeOnLoad">
        <!-- <div id="particles-js"></div> -->
        <div class="main_wrapper">
            <div class="content_wrapper">
                <div class="container">
                    <div class="content_block row no-sidebar">
                        <div class="fl-container">
                            <div class="row">
                                <div class="posts-block">
                                    <div class="contentarea">
                                        <div class="gt3_row_wrapper gt3_margin-top35">
                                            <div class="gt3_row_col3">
                                                <div class="gt3_block_wrapper2">
                                                    
                                                    <div class="page_title">
                                                        <h1>Contact information</h1>
                                                    </div>
                                                    <!-- .page_title -->
                                                    <article class="contentarea">
                                                        <p class=""><strong>Center for Robust Decision
                                                                making on Climate and Energy Policy</strong><br>5735
                                                            South Ellis
                                                            Avenue, 2nd Floor<br>Chicago, IL, 60637</p>
                                                        <p class="">Email: <a href="mailto:rdcep-info@uchicago.edu"
                                                                target="_blank">rdcep-info@uchicago.edu</a><br>Phone:&nbsp;(773)&nbsp;834-1726<br>Fax:&nbsp;(773)
                                                            834-6818</p>
                                                    </article>
                                                </div>
                                            </div>

                                            <div class="gt3_row_col4">
                                                <div class="gt3_block_wrapper2">
                                                    <iframe width="600" height="250" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/view?zoom=17&center=41.7905951%2C-87.60100490000002&key=AIzaSyAChgLMydtgwG9_Se3-Lt05BBzvekEn4u8" allowfullscreen></iframe>
                                                </div>
                                            </div>

                                        </div>

                                        <article class="contentarea">
                                            <p class=""><strong>Directions:</strong> The
                                                main offices of our center are located in the Computation Institute at
                                                the
                                                University of Chicago. To reach the Computation Institute enter the
                                                main door of the Searle building on Ellis Ave. Proceed down the ramp and
                                                turn right to find the elevator on your left. Take the elevator to the
                                                2nd
                                                floor and the Computation Institute main entrance will be down the hall
                                                to
                                                the right. This path is also a wheelchair-accessible route.</p>
                                        </article>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clear">&nbsp;</div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block customscript %}
<!-- <script type="text/javascript" src="{% static 'us_energy_viz/js/particles.js' %}"></script>

<link rel="stylesheet" href="{% static 'us_energy_viz/css/themes/default/default.css' %}" type="text/css"
    media="screen" />
<script>
    jQuery(document).ready(function ($) {
        particleBody_init();
        
    });
</script> -->
{% endblock %}

us_energy_viz/templates/us_energy_viz/footer.html
{% load static %}

<footer class="main_footer">
    <div class="main_footer_wrapper">
        <div class="container">

            <div class="gt3_row_wrapper gt3_margin-top35">
                <div class="gt3_row_col1">
                    <div class="gt3_block_wrapper">
                        <a href="http://www.rdcep.org/" target="_blank"><img
                                src="{% static 'us_energy_viz/img/rdcep.png' %}" class="img2preload"
                                alt="The Center for Robust Decision-making on Climate and Energy Policy (RDCEP)"
                                title="The Center for Robust Decision-making on Climate and Energy Policy (RDCEP)"
                                width="40%"></a>

                        <img src="{% static 'us_energy_viz/img/nsf_logo.png' %}"
                            class="freezeframe-responsive gt3_text_image"
                            style="float:right;width: 80px;height: 80px;display: block;border-radius: 100%;left: 0;top: 2px;margin-right:18%;"
                            alt="">
                    </div>
                </div>

                <div class="gt3_row_col2">
                    <div class="gt3_block_wrapper">
                        <a href="https://rcc.uchicago.edu/" target="_blank">
                            <img src="{% static 'us_energy_viz/img/rcc_powered_maroon.png' %}" class="img2preload"
                                alt="Research Computing Center (RCC) at The University of Chicago"
                                title="Research Computing Center (RCC) at The University of Chicago" width="100%">
                        </a>                        
                    </div>

                </div>      

            </div>

            <div>
                <ul class="funding_resources">
                    <li>Funding for this project was provided by the National Science
                        Foundation through a grant under
                        the Decision-making Under Uncertainty (DMUU) program, grant
                        <b>#SES-0951756</b>. Software copyright &copy; {% now 'Y' %} Nathan Matteson and the <a
                            href="https://rcc.uchicago.edu/" target="_blank">Research Computing Center (RCC) at
                            the University of Chicago</a>.</li>

                </ul>
            </div>

            <div class="clear"></div>

        </div>
    </div>
    <!-- .main_footer_wrapper -->
</footer>

us_energy_viz/templates/us_energy_viz/header.html
{% load static %}

<header class="container main_header">
    <div class="header_wrapper"> <!-- {% if request.path == "/" %}{% endif %} -->
        <div class="header_left_part">
            <div class="header_lp_wrapper">
                <a href="{% url 'us_energy_viz:index' %}" class="menu_logo">
                    <span class="logo_title">U.S. Energy History Visualization</span>
                    <!-- <img src="{% static 'us_energy_viz/img/us-energy-viz.png' %}" alt="" width="450" class="logo_def">
                    <img src="{% static 'us_energy_viz/img/retina/us-energy-viz.png' %}" alt="" width="450" class="logo_retina"> -->
                </a>
                <!--<div class="slogan"> Visualization of US Energy Consumption</div>-->
                <!-- .slogan -->
            </div>
        </div>
        <!-- .header_left_part -->
        <div class="header_right_part">
            <div class="header_rp_wrapper">
                <div class="center_trigger"></div>
                <nav class="main_nav">
                    <div class="menu-main-menu-container">
                        <ul class="menu">
                            <li class="menu-item"><a href="{% url 'us_energy_viz:about_us' %}">About</a></li>
                             <li class="menu-item"><a href="{% url 'us_energy_viz:charts' %}">Charts</a></li>
                            <li class="menu-item"><a href="{% url 'us_energy_viz:license' %}">License</a></li>
                            <li class="menu-item"><a href="{% url 'us_energy_viz:contact' %}">Contact</a></li>
                        </ul>
                    </div>
                </nav>
            </div>
        </div>
        <!-- .header_right_part -->
    </div>
</header>

us_energy_viz/templates/us_energy_viz/license.html
{% extends 'us_energy_viz/base.html' %}

{% load static %}

{% block title %}
License
{% endblock %}

{% block home_content %}
<div class="body_wrapper">
    <div class="site_wrapper fadeOnLoad">
        <!-- <div id="particles-js"></div> -->
        <div class="main_wrapper">
            <div class="content_wrapper">
                <div class="container">
                    <div class="content_block row no-sidebar">
                        <div class="fl-container">
                            <div class="row">
                                <div class="posts-block">
                                    <div class="contentarea">
                                        <div class="page_title">
                                            <h1>License information</h1>
                                        </div>
                                        <!-- .page_title -->

                                        <article class="contentarea">
                                            <p>Licensed for public use under the Apache License, Version 2.0 (the
                                                <span style="font-family:sans-serif;font-weight: bold;">&#8220;</span>License<span style="font-family:sans-serif;font-weight: bold;">&#8221;</span>).</p>
                                            <p>You may obtain a copy of the License at
                                                http://www.apache.org/licenses/LICENSE-2.0 You may not use this file
                                                except in compliance with the License. Unless required by applicable law
                                                or agreed to in writing, software distributed under the License is
                                                distributed on an <span style="font-family:sans-serif;font-weight: bold;">&#8220;</span>AS IS<span style="font-family:sans-serif;font-weight: bold;">&#8221;</span> basis, without warranties or conditions of any
                                                kind, either express or implied. See the License for the specific
                                                language governing permissions and limitations under the License.</p>
                                        </article>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="clear">&nbsp;</div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block customscript %}
<!-- <script type="text/javascript" src="{% static 'us_energy_viz/js/particles.js' %}"></script>

<link rel="stylesheet" href="{% static 'us_energy_viz/css/themes/default/default.css' %}" type="text/css"
    media="screen" />
<script>
    jQuery(document).ready(function ($) {
        particleBody_init();
        
    });
</script> -->
{% endblock %}

us_energy_viz/templates/us_energy_viz/preloader.html
<div class="preloader">
    <div class="preloader_content">
        <span>LOADING</span>
        <div class="preloader_line">
            <div class="preloader_line_bar1"></div>
            <div class="preloader_line_bar2"></div>
        </div>
    </div>
</div>